
      Begin ChemEQ Solver for PMDI_20lb_foam_1T_reaction_model

         Relative Tolerance = 1e-3
         Absolute Tolerance = 1e-6

         species FOAMA  = 0.45
         species FOAMB  = 0.15
         species FOAMC  = 0.40
         species CHAR   = 0.0
         species CO2    = 0.0
         species HMWO   = 0.0
         species LMWO   = 0.0

         ODE solver = CVODE

      End ChemEQ Solver for PMDI_20lb_foam_1T_reaction_model
